"""Audit `end:XXXX` cfg directives for v2 redundancy.

For each cfg `func` with an explicit `end:`, decode the function body
twice using v2's decode_function:

  1. With the cfg-declared `end:` enforced.
  2. With `end=None` so v2 follows every branch/fall-through.

Compare the set of decoded PCs. Three buckets:

  - REDUNDANT: pass 2's PC set equals pass 1's. The decoder would stop
    naturally (RTS/RTL/RTI terminates every path within the cfg-end
    range) without the directive. Safe to remove.

  - LOAD_BEARING: pass 2 reaches PCs strictly outside pass 1. The
    directive is preventing decoder drift into adjacent code. KEEP.

  - EXTENDED_BY_END: pass 1 covers PCs strictly outside pass 2. The
    directive is extending the body past where the decoder would
    naturally stop (D1-shape — usually obsolete in v2 because the
    decoder imports branch targets past `end:`, but here the user
    wrote `end:` to FORCE inclusion).

  - DECODE_ERROR: one or both decodes threw. Cannot judge.

Run with:
  python tools/audit_end_directive_redundancy.py --rom smw.sfc --cfg-dir recomp

Writes tools/audit_end_directive_redundancy_report.md with per-bank
sections, each function categorized.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import sys
from dataclasses import dataclass
from typing import List, Optional, Set, Tuple

_THIS_DIR = pathlib.Path(__file__).resolve().parent
_REPO_ROOT = _THIS_DIR.parent
_SNESRECOMP = _REPO_ROOT / "snesrecomp"
for p in (str(_SNESRECOMP), str(_SNESRECOMP / "tools"), str(_SNESRECOMP / "recompiler")):
    if p not in sys.path:
        sys.path.insert(0, p)

from snes65816 import load_rom  # noqa: E402
from v2.cfg_loader import load_bank_cfg  # noqa: E402
from v2.decoder import decode_function  # noqa: E402


@dataclass
class EndAudit:
    bank: int
    addr16: int
    fn_name: str
    cfg_end: int
    pcs_with_end: Optional[Set[int]] = None
    pcs_without_end: Optional[Set[int]] = None
    error_with_end: Optional[str] = None
    error_without_end: Optional[str] = None

    @property
    def category(self) -> str:
        if self.error_with_end or self.error_without_end:
            return "DECODE_ERROR"
        a, b = self.pcs_with_end, self.pcs_without_end
        if a is None or b is None:
            return "DECODE_ERROR"
        if a == b:
            return "REDUNDANT"
        if a - b:
            # pass-1 reached PCs that pass-2 did not — cfg end: is EXTENDING
            # the body past where natural decode would stop.
            return "EXTENDED_BY_END"
        # pass-2 reached PCs that pass-1 did not — cfg end: is BLOCKING drift
        return "LOAD_BEARING"

    @property
    def delta_pcs(self) -> Set[int]:
        """PCs in one set but not the other. For EXTENDED_BY_END these are
        the PCs the cfg end: rescues from being dropped; for LOAD_BEARING
        these are the PCs the cfg end: prevents from being decoded."""
        a = self.pcs_with_end or set()
        b = self.pcs_without_end or set()
        return (a ^ b)


_FUNC_LINE_RE = re.compile(
    r"^func\s+(\S+)\s+([0-9a-fA-F]+)\s+end:([0-9a-fA-F]+)"
)
_BANK_RE = re.compile(r"bank([0-9a-fA-F]+)\.cfg$")


def _try_decode(rom, bank, start, end):
    try:
        graph = decode_function(rom, bank, start, 1, 1, end=end)
        return set(graph.insns.keys()), None
    except Exception as e:
        return None, f"{type(e).__name__}: {e}"


def audit_bank(rom: bytes, bank: int, cfg_path: pathlib.Path) -> List[EndAudit]:
    audits: List[EndAudit] = []
    cfg = load_bank_cfg(str(cfg_path))
    for entry in cfg.entries:
        if entry.end is None:
            continue
        start16 = entry.start & 0xFFFF
        end16 = entry.end & 0xFFFF
        a = EndAudit(
            bank=bank,
            addr16=start16,
            fn_name=entry.name,
            cfg_end=end16,
        )
        a.pcs_with_end, a.error_with_end = _try_decode(rom, bank, start16, end16)
        a.pcs_without_end, a.error_without_end = _try_decode(rom, bank, start16, None)
        audits.append(a)
    return audits


def _format_report(all_audits: List[EndAudit]) -> str:
    lines = ["# `end:` directive redundancy audit",
             "",
             "Generated by `tools/audit_end_directive_redundancy.py`.",
             "",
             "## Summary",
             ""]
    by_cat: dict = {}
    for a in all_audits:
        by_cat.setdefault(a.category, []).append(a)
    total = len(all_audits)
    lines.append(f"- Total `func` with `end:`: **{total}**")
    for cat in ("REDUNDANT", "EXTENDED_BY_END", "LOAD_BEARING", "DECODE_ERROR"):
        n = len(by_cat.get(cat, []))
        lines.append(f"- {cat}: **{n}**")
    lines.append("")
    lines.append("## Per category")
    lines.append("")
    for cat in ("REDUNDANT", "EXTENDED_BY_END", "LOAD_BEARING", "DECODE_ERROR"):
        entries = by_cat.get(cat, [])
        if not entries:
            continue
        lines.append(f"### {cat} ({len(entries)})")
        lines.append("")
        if cat == "REDUNDANT":
            lines.append("These `end:` directives can likely be removed — v2's decoder "
                         "covers the same PCs without the directive. Test each individually "
                         "under the per-change loop.")
        elif cat == "EXTENDED_BY_END":
            lines.append("Cfg `end:` extends the body PAST where the decoder naturally stops. "
                         "Verify the extension is still needed in v2 (the D1 case — "
                         "ParseLevelSpriteList_Entry2 — fell here and turned out to be obsolete).")
        elif cat == "LOAD_BEARING":
            lines.append("Cfg `end:` prevents the decoder from drifting into adjacent code. "
                         "DO NOT remove without restructuring (likely a real boundary).")
        elif cat == "DECODE_ERROR":
            lines.append("Decode threw on one or both passes — cannot judge. Investigate manually.")
        lines.append("")
        lines.append("| Bank | PC | Name | cfg end: | Δ PCs |")
        lines.append("|---|---|---|---|---|")
        for a in sorted(entries, key=lambda x: (x.bank, x.addr16)):
            delta = len(a.delta_pcs)
            lines.append(
                f"| ${a.bank:02X} | ${a.addr16:04X} | {a.fn_name} | "
                f"${a.cfg_end:04X} | {delta} |"
            )
        lines.append("")
    return "\n".join(lines) + "\n"


_END_TOKEN_RE = re.compile(r"\s+end:[0-9a-fA-F]+")


def _apply_redundant_removals(cfgs, by_cat) -> int:
    """Strip the ` end:XXXX` token from cfg `func` lines flagged REDUNDANT.

    Matches by (bank, addr16) pair against each `func NAME ADDR end:HEX ...`
    line. Preserves the rest of the line (signature, AUTO/MANUAL comment).
    Reads + writes as bytes so CRLF / LF / mixed endings survive unchanged
    — Windows-edited cfg files use CRLF and naive splitlines/join would
    normalize to LF, causing git to register every line as a rewrite.
    Returns the count of lines modified.
    """
    redundant = by_cat.get("REDUNDANT", [])
    by_bank: dict = {}
    for a in redundant:
        by_bank.setdefault(a.bank, {})[a.addr16] = a
    modified_total = 0
    end_token_bytes = re.compile(rb"\s+end:[0-9a-fA-F]+")
    func_line_bytes = re.compile(rb"^func\s+\S+\s+([0-9a-fA-F]+)")
    for cfg_path in cfgs:
        m = _BANK_RE.search(cfg_path.name)
        if not m:
            continue
        bank = int(m.group(1), 16)
        if bank not in by_bank:
            continue
        targets = by_bank[bank]
        raw = cfg_path.read_bytes()
        # splitlines(True) keeps the trailing EOL on each line so we can
        # reattach unchanged when joining back.
        out_chunks = []
        modified = 0
        for line in raw.splitlines(True):
            ms = func_line_bytes.match(line)
            if ms:
                addr16 = int(ms.group(1), 16) & 0xFFFF
                if addr16 in targets:
                    new_line, n = end_token_bytes.subn(b"", line, count=1)
                    if n > 0:
                        modified += 1
                        line = new_line
            out_chunks.append(line)
        if modified:
            cfg_path.write_bytes(b"".join(out_chunks))
            print(f"  {cfg_path.name}: stripped {modified} redundant end: tokens")
            modified_total += modified
    return modified_total


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--rom", required=True)
    p.add_argument("--cfg-dir", default="recomp")
    p.add_argument("--out", default="tools/audit_end_directive_redundancy_report.md")
    p.add_argument("--apply", action="store_true",
                   help="Strip end: tokens classified REDUNDANT from cfg files")
    args = p.parse_args()

    rom = load_rom(args.rom)
    cfg_dir = pathlib.Path(args.cfg_dir)
    cfgs = sorted(cfg_dir.glob("bank*.cfg"))

    all_audits: List[EndAudit] = []
    for cfg_path in cfgs:
        m = _BANK_RE.search(cfg_path.name)
        if not m:
            continue
        bank = int(m.group(1), 16)
        all_audits.extend(audit_bank(rom, bank, cfg_path))

    report = _format_report(all_audits)
    out_path = pathlib.Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report, encoding="utf-8")
    print(f"Wrote {out_path}")
    print()
    print(report.splitlines()[3:12])  # echo Summary lines
    by_cat: dict = {}
    for a in all_audits:
        by_cat.setdefault(a.category, []).append(a)
    print()
    for cat in ("REDUNDANT", "EXTENDED_BY_END", "LOAD_BEARING", "DECODE_ERROR"):
        n = len(by_cat.get(cat, []))
        print(f"  {cat}: {n}")
    if args.apply:
        print()
        print("--apply: stripping REDUNDANT end: tokens from cfg files...")
        n = _apply_redundant_removals(cfgs, by_cat)
        print(f"Total lines modified: {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
